package compilador.lexico;

public enum ClasseToken {
    Identificador,
    Inteiro,
    PalavraReservada,
    EOF,
    Mais,
    Menos,
    Divisao,
    Multiplicacao,
    Igualdade,
    Atribuicao,
    Maior,
    MaiorIgual,
    Menor,
    MenorIgual,
    Diferente,
    DoisPontos,
    PontoVirgula,
    Virgula,
    AbreParenteses,
    FechaParenteses,
    Ponto,
    String,
}
